# Generated by Django 4.1.7 on 2023-04-10 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_notification_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="fromUser",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fromUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
