# Generated by Django 4.1.7 on 2023-04-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_message_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="user_avatar",
            field=models.ImageField(default="avatar.svg", null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="message",
            name="username",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
