# Generated by Django 4.1.7 on 2023-04-10 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_following_follower"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="followingUsersModel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
