# Generated by Django 4.1.7 on 2023-04-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(default="#", max_length=200),
        ),
    ]
