# Generated by Django 4.1.7 on 2023-04-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(default="text", max_length=200),
        ),
    ]
