# Generated by Django 4.1.7 on 2023-04-13 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_question_question_image_question_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="completed_by",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
