# Generated by Django 4.1.7 on 2023-04-26 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_message_user_avatar_message_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="down_votes",
            field=models.ManyToManyField(
                blank=True, related_name="down_votes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="up_votes",
            field=models.ManyToManyField(
                blank=True, related_name="up_votes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
